"""empty message

Revision ID: 20ba064a3090
Revises: 7d4ce024b3ff
Create Date: 2025-09-04 15:10:31.479424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ba064a3090'
down_revision: Union[str, Sequence[str], None] = '7d4ce024b3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('days_id_key'), 'days', type_='unique')
    op.drop_constraint(op.f('notes_id_key'), 'notes', type_='unique')
    op.drop_constraint(op.f('task_status_id_key'), 'task_status', type_='unique')
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('task_status_id_key'), 'task_status', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('notes_id_key'), 'notes', ['id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('days_id_key'), 'days', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###