"""Add unique to user and date in days table

Revision ID: eaf675f956fb
Revises: c973491dba64
Create Date: 2025-08-04 13:35:23.447459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf675f956fb'
down_revision: Union[str, Sequence[str], None] = 'c973491dba64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_date', 'days', ['user', 'date'])
    op.create_unique_constraint(None, 'days', ['id'])
    op.create_unique_constraint(None, 'notes', ['id'])
    op.create_unique_constraint(None, 'task_status', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_status', type_='unique')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_constraint(None, 'days', type_='unique')
    op.drop_constraint('unique_user_date', 'days', type_='unique')
    # ### end Alembic commands ###
