"""add unique to task and day in task_status table

Revision ID: 7d4ce024b3ff
Revises: eaf675f956fb
Create Date: 2025-08-04 15:03:21.131384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4ce024b3ff'
down_revision: Union[str, Sequence[str], None] = 'eaf675f956fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_day_unique', 'task_status', ['task', 'day'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_day_unique', 'task_status', type_='unique')
    # ### end Alembic commands ###
