"""empty message

Revision ID: 474ae2751628
Revises: 2ab6212da7fe
Create Date: 2025-07-16 14:26:05.640116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474ae2751628'
down_revision: Union[str, Sequence[str], None] = '2ab6212da7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['user'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'user')
    # ### end Alembic commands ###
